spring:
  profiles:
    active: ${PROFILE}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
---

logging:
  level:
    org:
      springframework:
        web: DEBUG


